name: lib_soma_front
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  go_router: ^13.2.2
  flutter_riverpod: ^2.5.1

  cupertino_icons: ^1.0.2
  dio: ^5.7.0
  logger: ^2.4.0
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/loading.gif
